spring:
  application:
    name: springSession1
  data:
    redis:
      host: 192.168.31.128
      port: 6379
      username: poly
      password: 1234
  session:
    redis:
      flush-mode: on_save


server:
  port: 25000
  servlet:
    session:
      timeout: 10m